/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low":"#f6f3f2",
        "on-tertiary-container":"#00646f",
        "error-container":"#ffdad6",
        "secondary":"#5d5f5f",
        "on-secondary-fixed":"#1a1c1c",
        "surface-container-lowest":"#ffffff",
        "tertiary-fixed-dim":"#00daf0",
        "status-warning":"#FACC15",
        "secondary-fixed":"#e2e2e2",
        "surface-container":"#f0eded",
        "on-tertiary-fixed":"#001f24",
        "inverse-surface":"#313030",
        "surface-variant":"#e5e2e1",
        "surface":"#fcf9f8",
        "on-primary-container":"#6f5800",
        "error":"#ba1a1a",
        "tertiary":"#006874",
        "on-primary-fixed-variant":"#574400",
        "secondary-fixed-dim":"#c6c6c7",
        "on-background":"#1c1b1b",
        "border-subtle":"#E5E7EB",
        "on-surface":"#1c1b1b",
        "on-secondary":"#ffffff",
        "surface-container-high":"#eae7e7",
        "primary":"#745b00",
        "primary-fixed-dim":"#f1c100",
        "inverse-primary":"#f1c100",
        "surface-tint":"#745b00",
        "surface-container-highest":"#e5e2e1",
        "inverse-on-surface":"#f3f0ef",
        "secondary-container":"#dcdddd",
        "tertiary-container":"#01e8ff",
        "on-primary-fixed":"#241a00",
        "on-error":"#ffffff",
        "on-tertiary":"#ffffff",
        "outline":"#80765f",
        "background":"#fcf9f8",
        "status-success":"#22C55E",
        "tertiary-fixed":"#95f1ff",
        "surface-white":"#FFFFFF",
        "on-primary":"#ffffff",
        "on-surface-variant":"#4e4632",
        "on-error-container":"#93000a",
        "on-secondary-container":"#5f6161",
        "outline-variant":"#d1c5ab",
        "on-secondary-fixed-variant":"#454747",
        "primary-container":"#ffcd11",
        "primary-fixed":"#ffe08a",
        "surface-dim":"#dcd9d9",
        "surface-bright":"#fcf9f8",
        "status-error":"#EF4444",
        "on-tertiary-fixed-variant":"#004f57"
      },
      borderRadius: {
        "DEFAULT":"0.25rem",
        "lg":"0.5rem",
        "xl":"0.75rem",
        "full":"9999px"
      },
      spacing: {
        "xl":"48px",
        "sm":"16px",
        "md":"24px",
        "container-max":"1440px",
        "base":"4px",
        "xs":"8px",
        "lg":"32px",
        "gutter":"24px"
      },
      fontFamily: {
        "stat-number":["Inter", "sans-serif"],
        "label-bold":["Inter", "sans-serif"],
        "headline-lg-mobile":["Inter", "sans-serif"],
        "headline-md":["Inter", "sans-serif"],
        "headline-lg":["Inter", "sans-serif"],
        "body-sm":["Inter", "sans-serif"],
        "body-lg":["Inter", "sans-serif"],
        "display-lg":["Inter", "sans-serif"],
        "headline-sm":["Inter", "sans-serif"],
        "body-md":["Inter", "sans-serif"]
      },
      fontSize: {
        "stat-number":["36px",{"lineHeight":"44px","fontWeight":"800"}],
        "label-bold":["12px",{"lineHeight":"16px","letterSpacing":"0.05em","fontWeight":"700"}],
        "headline-lg-mobile":["24px",{"lineHeight":"32px","fontWeight":"700"}],
        "headline-md":["24px",{"lineHeight":"32px","fontWeight":"700"}],
        "headline-lg":["32px",{"lineHeight":"40px","letterSpacing":"-0.01em","fontWeight":"700"}],
        "body-sm":["14px",{"lineHeight":"20px","fontWeight":"400"}],
        "body-lg":["18px",{"lineHeight":"28px","fontWeight":"400"}],
        "display-lg":["48px",{"lineHeight":"56px","letterSpacing":"-0.02em","fontWeight":"800"}],
        "headline-sm":["20px",{"lineHeight":"28px","fontWeight":"600"}],
        "body-md":["16px",{"lineHeight":"24px","fontWeight":"400"}]
      }
    },
  },
  plugins: [],
}
